### ISSUE TITLE
"No audio files found" for a valid cue

### ISSUE THREAD

**Issue by SafEight** [jeanslack/FFcuesplitter#33]
Getting an FFCueSplitterError with the following code: 

```python
split = FileSystemOperations(
    filename = absolute_cue_path
    outputformat = "opus",
    overwrite = "always",
    outputdir = absolute_album_path,
    ffmpeg_add_params = "-b:a 192k -metadata filename=folder.jpg",
    )
split.work_on_temporary_directory()
```

```shell
WARNING:root:Not found: `(01) [Dear, friends] Opening-.flac`. Track is skipped.
WARNING:root:Not found: `(02) [Dear, friends] Phamtom.flac`. Track is skipped.
WARNING:root:Not found: `(03) [Dear, friends] VSレミリア in Last Word.flac`. Track is skipped.
WARNING:root:Not found: `(04) [Dear, friends] Ending.flac`. Track is skipped.
Traceback (most recent call last):
    ...
    split = FileSystemOperations(
            ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ffcuesplitter\cuesplitter.py", line 156, in __init__
    self.open_cuefile()  # requires to open cue file first
    ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\ffcuesplitter\cuesplitter.py", line 327, in open_cuefile
    self.deflacue_object_handler()
  File "C:\Python311\Lib\site-packages\ffcuesplitter\cuesplitter.py", line 246, in deflacue_object_handler
    raise FFCueSplitterError('No audio files found!')
```

I've tested it with other albums and it works flawlessly otherwise. It's just this one that gives trouble. The cue plays correctly when using mpv, so I don't believe it's an issue with the files. I've uploaded the [relevant files here](https://pixeldrain.com/u/8W8JASHY) for replication.

**Comment by jeanslack** [comment]
The CUE file data is incomplete or incorrect. 
This is what I suppose should be done:
```
REM GENRE Game
REM DATE 2006.05.21 
PERFORMER "Dear, friends" 
TITLE "東方夜詠月 - Dear,Music Another side -" 
FILE "Dear, friends - 東方夜詠月 - Dear,Music Another side -.flac" WAVE
  TRACK 01 AUDIO 
    TITLE "Opening-" 
    PERFORMER "Shinya" 
    INDEX 01 00:00:00 
  TRACK 02 AUDIO 
    TITLE "Phamtom" 
    PERFORMER "nozomu" 
    INDEX 01 01:10:30 
  TRACK 03 AUDIO 
    TITLE "VSレミリア in Last Word" 
    PERFORMER "Shinya" 
    INDEX 01 06:34:35 
  TRACK 04 AUDIO 
    TITLE "Ending" 
    PERFORMER "nozomu" 
    INDEX 01 09:32:50 
```
Replace the contents of the CUE file with the data above, save the file and you will see that it will work.

Then perform the splitting operation:
```python
>>> from ffcuesplitter.user_service import FileSystemOperations
```
```python
>>> split = FileSystemOperations(
              filename='Dear, friends - 東方夜詠月 - Dear,Music Another side -.cue', 
              outputformat='opus', 
              outputdir='.', 
              overwrite='always', 
              ffmpeg_add_params='-b:a 192k -metadata filename=folder.jpg',
              )
```
```python
>>> split.work_on_temporary_directory()
```

**Comment by SafEight** [comment]
I had no idea the flac file contained the cuesheet data.
